### PR TITLE
package_name: make it possible to latest versions since gitlab 10.0

### PR DESCRIPTION
**Pull request by paulRbr**

### CODE REVIEW

**Comment by riemers** [comment]
Thanks for the update!

**Comment by paulRbr** [comment]
No problem :). I have tested it against a Debian system but didn't have the chance to test it against RHEL if you can validate than it would be great.

**Comment by riemers** [comment]
Don't have a rhel nearby, debian here too. But should still work i presume, if not they can always make a ticket/pr.

**Comment by paulRbr** [comment]
Looks good thanks again for the merge

**Pull request merged**
