### PR TITLE
Update list-configured-runners-unix.yml

### PR DESCRIPTION
**Pull request by krousenick**
fix for filtering out invalid json

### CODE REVIEW

**Comment by guenhter** [comment]
Hi, why is the json invalid?

**Comment by krousenick** [comment]
Hey, 

Thanks for getting back to me. So I am running FIPS runners and when you run the command `gitlab-runner --log-format json list` you get more than just json, it also prints out:

INFO[0000] FIPS mode is enabled. Using an external SSL library.
{"arch":"amd64","level":"info","msg":"Runtime platform","os":"linux","pid":150707,"revision":"374d34fd","time":"2024-12-03T14:34:09-05:00","version":"17.6.0"}

**Comment by guenhter** [comment]
Thx for the clarification.

**Comment by guenhter** [comment]
Thx for this contribution

**Comment by guenhter** [comment]
@krousenick I have to revert this, because that one breaks a lot of other pipelines.

**Pull request merged**
