### PR TITLE
Update to python 3.9

### PR DESCRIPTION
**Pull request by riemers**
Lets see if travis works again too, that changed. Also ansible galaxy totally revamped/changed too.. ugh

### CODE REVIEW

**Comment by guenhter** [comment]
Fixing the CI will be very interesting. For Linux I currently struggle with all the parts which requires Systemd....

**Comment by riemers** [comment]
https://forum.ansible.com/t/lost-all-history-of-ansible-role-after-delete-of-a-another-role/1753

Yeah, almost up to the point to just throw in the towel.. :(

**Comment by guenhter** [comment]
Oh sh***

**Comment by guenhter** [comment]
Chances are there, that I might be responsible for this: https://github.com/riemers/ansible-gitlab-runner/pull/286  in the file `meta/main.yml` I added one line, which could have impacted something...

**Comment by riemers** [comment]
Nah, i doubt it will.. this is pure the whole change with ansible galaxy.. features missing, removed functionality, outdated docs. Missing information. Nothing new but it is just a lot.. lets hope someone can fix that part for me so we are at least back in business, then only travis remains.

**Comment by riemers** [comment]
I'll check this later when i have some more time.

**Pull request closed without merging**
