### PR TITLE
Code cosmetics

### PR DESCRIPTION
**Pull request by guenhter**
Just some small cosmetic changes. No functionality is touched, just renamed files, tasks and extract some constructs in order to reduce them.

This is just the preparation PR for another feature I want to implement: unregistering runners which are currently registered but not longer configured.

### CODE REVIEW

**Comment by riemers** [comment]
You still busy with this? I also like all the lower cases, didn't even see that one ;) (if so, put it to draft otherwise)

**Comment by guenhter** [comment]
I'm done.

**Comment by riemers** [comment]
I've send you an invite, so you have the option to work on the thing you are mentioning ;)

**Comment by guenhter** [comment]
:) this is great. I'd gladly help out reviewing and merging other MR's but I don't like to do this on my own (somehow for me this has a smell of "I know it anyway better than the rest"). Maybe you still could have a look at my requests.

**Comment by riemers** [comment]
Yeah no problem, its all best effort here :) but i need at least someone with enough ansible knowhow ;) i use ansible every day almost.. but yeah work is not pleasure sometimes :)

**Pull request merged**
