### PR TITLE
Allow running role without global become: true

### PR DESCRIPTION
**Pull request by easbar**
Fixes https://github.com/riemers/ansible-gitlab-runner/issues/70.

### CODE REVIEW

**Comment by easbar** [comment]
Maybe you can help here: The role still does not behave as with setting `become: true` globally: I think the settings in `/etc/gitlab-runner/config.toml` are not updated (and instead there is `home/<user>/.gitlab-runner/config.toml` (which does not seem to get updated when changing some runner settings and re-running the role).

**Comment by riemers** [comment]
as far as i know it uses the /etc/gitlab-runner/config.toml and it does require root for that. As i see my files are owned by root. So it needs a become there too.

**Comment by easbar** [comment]
> as far as i know it uses the /etc/gitlab-runner/config.toml and it does require root for that. As i see my files are owned by root.

Yes

>  So it needs a become there too.

but where ?

**Comment by easbar** [comment]
> but where ?

I think I found it: Had to make sure `gitlab-runner register` is run as root: https://github.com/riemers/ansible-gitlab-runner/pull/71/commits/c94054cfb1bdc38480c1f8f7d7ebe9806b007b38 

Now it does what I think it should :)

**Comment by riemers** [comment]
Good question, hence this PR since i have not tried that before :)

**Comment by riemers** [comment]
So you tested it too like that? Presume you did, just checking.

**Comment by easbar** [comment]
Yes, I ran this PR without global `become: true` on a system without gitlab-runner. It got installed fine and a runner was created (according to my settings). It created `/etc/gitlab-runner/config.toml` and afterwards I tried changing some settings and replaying the role which also worked. I also tried switching the `state` between `present` and `absent` and that worked too.

**Comment by riemers** [comment]
Sounds like we need more people that make changes, offer PR's and actually tested it. i'll merge it.

**Pull request merged**
