### PR TITLE
Windows support

### PR DESCRIPTION
**Pull request by mschmieder**
Hey Erik-Jan,

I needed to extend your role to also support windows since we have to maintain windows runners as well. I followed your pretty impressive work as much as I could - but I had to copy quite some bits and pieces to have the windows specific ansible modules addressed correctly. There currently also seems to be a **bug** in ansible with the **assemble** command that is not working on windows properly, therefore I had to mimic the functionality using powershell commands.

I did test the role on our machines but was not able to integrate it into your **travis ci**.

Let me know what you think, I'd be happy to make adaptions if needed.

### CODE REVIEW

**Comment by riemers** [comment]
Did you also verify it with Unix? I see that you changed debian to Unix which is fine since it is supported by multiple. Then you also moved the url gitlab_runner_download_url to darwin / windows but i don't see a unix one. In the vars there is now for windows and darwin some defaults but not for Unix, where does it know how to get the url then? (might be overlooking something, just did a quick scan)

**Comment by mschmieder** [comment]
I did have a look at it but it seems you're using the different packaging systems (apt/rpm) to install on Linux-based systems and therefore you seem not to be using the downloaded package at all. That's why there is only definitions for Windows and MacOS. The Travis CI seems to be ok with the changes.

I'd love to add the windows tests as well, but I'm not sure how to provision a Windows machine out of the Windows box travis provides since I'm not able to switch the docker engine to run linux containers...

Do you have an idea on how to integrate this into the CI?

**Comment by mschmieder** [comment]
After several hours of testing I figured out a way on how to create a TravisCI using Windows. It is a pretty packed process therefore build time are little higher than your usual Darwin and Linux builds, but it seems to work fine:

The build process uses
- Windows 1809 Travis Base Image
- Install Windows-Subsystem-For-Linux with Ubuntu 18.04
- Creates a local Ansible user to login with winrm
- Uses Ansible windows prepare script to open all necessary ports to the machine
- Installs latest Ansible in WSL using pip3/python3
- Executes the tests using winrm on localhost
- creates a shell and docker-windows runner

**Comment by riemers** [comment]
Thats pretty damn awesome 👏 i'll merge this as i don't have any windows to test on and its too cool to not pass :)

**Pull request merged**
