### PR TITLE
:bug: Special handling on debian buster

### PR DESCRIPTION
**Pull request by nilskuhn**
Fixing problems on debian buster described here:
https://gitlab.com/gitlab-org/gitlab-runner/-/issues/4092
https://docs.gitlab.com/runner/install/linux-repository.html#disable-skel

### CODE REVIEW

**Comment by nilskuhn** [comment]
How long does it take to get this from galaxy?
At the moment I am pulling previous version. Or must this be triggered manually?

**Comment by riemers** [comment]
After i create a release, it should be picked up by galaxy..

**Comment by nilskuhn** [comment]
Thanks for releasing, but you mixed up the version numbers, I think.
Think my fix shouldn't introduce a major switch from v1.6.14 to v6.1.15 ;)

**Comment by riemers** [comment]
🙄 so it may seem. Changed now ;)

**Comment by riemers** [comment]
p.s. i never know when it is really grabbing the version, sometimes its a bit buggy but it will get there.

**Comment by nilskuhn** [comment]
ok, thanks!

**Comment by riemers** [comment]
had a . in front of it still, silly me. Not my day, manually imported, its there

**Pull request merged**
