### PR TITLE
ansible 2.16: add docker dependency

### PR DESCRIPTION
**Pull request by Stunkymonkey**
in ansible 2.16 the `docker_container` is no longer available. When installing the collection `community.docker` it works.

### CODE REVIEW

**Comment by riemers** [comment]
Although good to mention, this makes the docker mandatory for everyone, while this might not be the case, hence the empty array. You could just add a note and # note/mention the optional dependency?

**Comment by Stunkymonkey** [comment]
yes you are right. it is more an optional one. marked it as comment. or do you want this to be in the README?

**Comment by riemers** [comment]
Both options are fine, if it’s there to assist people in making a correct choice, then it’s good right :)
________________________________
Van: Felix Bühler ***@***.***>
Verzonden: Monday, August 12, 2024 9:09:41 PM
Aan: riemers/ansible-gitlab-runner ***@***.***>
CC: Erik-jan Riemers ***@***.***>; Comment ***@***.***>
Onderwerp: Re: [riemers/ansible-gitlab-runner] ansible 2.16: add docker dependency (PR #342)


yes you are right. it is more an optional one. marked it as comment. or do you want this to be in the README?

**Comment by Stunkymonkey** [comment]
@riemers of wow. there a quite a few linter errors showing up...

**Comment by riemers** [comment]
Doesn’t like comments? There is a PR with better linter support but it’s stalled atm..
________________________________
Van: Felix Bühler ***@***.***>
Verzonden: Monday, August 12, 2024 9:35:48 PM
Aan: riemers/ansible-gitlab-runner ***@***.***>
CC: Erik-jan Riemers ***@***.***>; Mention ***@***.***>
Onderwerp: Re: [riemers/ansible-gitlab-runner] ansible 2.16: add docker dependency (PR #342)


@riemers<https://github.com/riemers> of wow. there a quite a few linter errors showing up...

**Comment by Stunkymonkey** [comment]
@riemers do you suggest not touching the linter at all? then i simply remove the last commit.

**Comment by riemers** [comment]
you can touch it, as long as it stil works after wards, the test don't do much atm. Also need to get free credit but thats always a pain with the CI team

**Comment by Stunkymonkey** [comment]
will be fixed via #344

**Pull request closed without merging**
