### PR TITLE
fix cache_type variable check

### PR DESCRIPTION
**Pull request by besmirzanaj**

### CODE REVIEW

**Comment by riemers** [comment]
Are you not missing the #128 line?

**Comment by besmirzanaj** [comment]
I thought I did. resubmitting

**Comment by tauffredou** [comment]
I've tried to add the failing test but everything is still green.
@riemers how testing works ?

**Comment by riemers** [comment]
@tauffredou since the default "example" already has that value defined it didn't trigger anything. We should actually test with different setups too. But as everyone time is limited, i happened to be busy with some code for something else hence why i could jump on this too (those darn popups haha)

**Pull request merged**
