### PR TITLE
Fix update-config-runner | Add builds_dir and cache_dir options

### PR DESCRIPTION
**Pull request by GMartinez-Sisti**
I wanted to add builds_dir and cache_dir options, and realised that new options were not being reflected in the config.
The issue was with the `backrefs` configs set to true in `lineinfile`. When the entries didn't exist, the capture group was not available so Ansible wasn't adding them.
I also added `insertafter` so that the lines are after the main mandatory configurations.

Please let me know if it's ok. I love this role and wanted to contribute for a while.

Thanks!

### CODE REVIEW

**Comment by GMartinez-Sisti** [comment]
Fixes the issue I was having in https://github.com/riemers/ansible-gitlab-runner/issues/59

**Comment by GMartinez-Sisti** [comment]
Please don't merge this yet, I'm having a strange issue with the new folders.

I used the configs:
```yaml
build_dir: "/data/gitlab-runner/builds"
cache_dir: "/data/gitlab-runner/cache"
```

The folders are created properly:

```sh
~$ sudo ls -lha -R /data/gitlab-runner/
/data/gitlab-runner/:
total 16K
drwxrwx--- 4 root gitlab-runner 4.0K Jul  3 15:34 .
drwxr-xr-x 5 root root          4.0K Jul  3 15:34 ..
drwxrwx--- 2 root gitlab-runner 4.0K Jul  3 15:34 builds
drwxrwx--- 2 root gitlab-runner 4.0K Jul  3 15:34 cache
```

and gitlab-runner is executing with the correct user:

```sh
~$ sudo ps aux | grep gitlab-runner
root     16203  0.2  0.2  42280 27572 ?        Ssl  11:59   0:14 /usr/lib/gitlab-runner/gitlab-runner run --working-directory /home/gitlab-runner --config /etc/gitlab-runner/config.toml --service gitlab-runner --syslog --user gitlab-runner
```

However the job is failing with:
```sh
Running with gitlab-runner 11.10.0 (3001a600)
  on run01 ixHEBKtJ
Using Shell executor...
Running on run01...
mkdir: cannot create directory ‘/data/gitlab-runner’: Permission denied
mkdir: cannot create directory ‘/data/gitlab-runner’: Permission denied
ERROR: Job failed: exit status 1
```

Maybe it needs permissions on the parent `/data` folder, but that's strange.

I'll look up the source code for the runner and update this after.

**Comment by riemers** [comment]
Hence why i asked ishkulov too :)

**Comment by GMartinez-Sisti** [comment]
@riemers The problem is the parent folder permissions (in the example above /data). When parents folders already exist and gitlab-runner doesn't have permissions to traverse, this will happen.

 I think there are at least 2 options here:
1. Managing parent folder permissions is out of scope for this role, so we can perform a check and fail
1. We ensure that gitlab-runner has read permissions, but we might break security for the existing environment

What do you think?

**Comment by GMartinez-Sisti** [comment]
This is working now. I went with option one -> Managing parent folder permissions is out of scope for this role, so we can perform a check and fail.

**Pull request merged**
